# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7678e64e8370c2d908e64dda91f90a3d16c4daff1327f58ba7ee2db79c5421184d80ded9e59674cc43b550d3ebcc81e196b9950a33e5ab9eb6c450961994bad

test:
  secret_key_base: 6cd82d00e9724974eaa0b46ef70e387cdb8d585610dd35b238e68436ee4e53aad70fd757625abd8df70dd05a4179ac901d18b443eb774a79a62b39b14b4c4206

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
